### ISSUE TITLE
Google play service version

### ISSUE THREAD

**Issue by BrezhDev** [nisrulz/qreader#37]
Hello,

Can you use the version 10.2.0 for google service please ?

**Comment by nisrulz** [comment]
@BrezhDev I can, but it brings in 2 issues

1. I have to drop support for pre API 14 devices
2. There are a lot of issues I need to fix for the next release. I just have not been able to give the love QREader deserves because I have been occupied. 

If you want to update the google play services, I would suggest you check out the library code and add it as a module to your app. Update the google play services version and  you should be good.

**Comment by nisrulz** [comment]
The latest release has the dependencies updated. Closing this issue now.
